apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flux-web.fullname" . }}
  labels:
{{ include "flux-web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flux-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flux-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: READ_ONLY
            value: {{ .Values.readOnly | quote }}
          - name: NAMESPACES
            value: {{ .Values.namepaces | quote  }}
          - name: FLUX_URL
            value: {{ .Values.fluxUrl | quote }}
          - name: DEFAULT_NAMESPACE
            value: {{ .Values.defaultNamespace | quote  }}

            {{- if .Values.environment -}}
            {{- range $key, $val := .Values.environment }}
          - name: {{ if $key | regexMatch "^[^.-]+$" -}}
            {{- $key }}
            {{- else -}}
            {{- fail (join "Environment variables can not contain '.' or '-' Failed key: " ($key|quote)) -}}
            {{- end }}
            value: {{ tpl ($val | quote) $ }}
              {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.applicationPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
